-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 23:41:51 2020
-- Model: VizinhoOnline_v3    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vizinho_online
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vizinho_online` ;

-- -----------------------------------------------------
-- Schema vizinho_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vizinho_online` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `vizinho_online` ;

-- -----------------------------------------------------
-- Table `vizinho_online`.`CATEGORIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`CATEGORIES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`CATEGORIES` (
  `id_category` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `category_code` VARCHAR(200) NULL DEFAULT NULL,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  `delete_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `id_category_UNIQUE` (`id_category` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`FAVORITES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`FAVORITES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`FAVORITES` (
  `id_favorite` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `favorite_code` VARCHAR(45) NULL DEFAULT NULL,
  `favorite_status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_favorite`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`FEEDBACKS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`FEEDBACKS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`FEEDBACKS` (
  `id_feedback` INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `comment` VARCHAR(200) NULL DEFAULT NULL,
  `score` INT(11) NULL DEFAULT NULL,
  `create_date` DATETIME NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  `delete_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_feedback`),
  UNIQUE INDEX `id_feedback_UNIQUE` (`id_feedback` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`ITEMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`ITEMS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`ITEMS` (
  `id_item` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  `delete_date` DATETIME NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL COMMENT 'full description of the item',
  `tax_fee` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Price that will be charged by the item',
  `internal_notes` VARCHAR(200) NULL DEFAULT NULL COMMENT 'This field will be used by the system and administrators.',
  `feedback_score` INT(11) NULL DEFAULT NULL,
  `units` VARCHAR(45) NULL DEFAULT NULL,
  `loan_start_date` DATETIME NULL DEFAULT NULL,
  `loan_end_date` DATETIME NULL DEFAULT NULL,
  `replacement_cost` FLOAT NULL DEFAULT NULL,
  `id_status` INT(11) NOT NULL,
  PRIMARY KEY (`id_item`, `id_status`),
  UNIQUE INDEX `id_Item_UNIQUE` (`id_item` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`USERS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`USERS` (
  `id_user` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `age` INT(11) NULL DEFAULT NULL,
  `ranking` VARCHAR(45) NULL DEFAULT NULL,
  `cellphone` INT(15) NULL,
  `create_date` DATETIME NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  `delete_date` DATETIME NULL DEFAULT NULL,
  `image_id` INT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`ITEMS_FEEDBACK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`ITEMS_FEEDBACK` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`ITEMS_FEEDBACK` (
  `id_item_feedback` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `create_date` DATETIME NOT NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  `delete_date` DATETIME NULL DEFAULT NULL,
  `id_item` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `id_feedback` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `id_user` INT(5) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id_item_feedback`, `id_item`, `id_feedback`, `id_user`),
  UNIQUE INDEX `id_Item_feedback_UNIQUE` (`id_item_feedback` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`ITEM_CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`ITEM_CATEGORY` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`ITEM_CATEGORY` (
  `id_item_category` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'foreign key category',
  `create_date` DATETIME NOT NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  `delete_date` DATETIME NULL DEFAULT NULL,
  `id_category` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `id_item` INT(5) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id_category`, `id_item`),
  UNIQUE INDEX `id_item_category_UNIQUE` (`id_item_category` ASC),
  INDEX `fk_ITEM_CATEGORY_CATEGORIES1_idx` (`id_category` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`LOCATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`LOCATIONS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`LOCATIONS` (
  `id_location` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `apartment_number` INT(11) NOT NULL,
  `build` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `intercom_branch` INT(11) NULL DEFAULT NULL,
  `id_user` INT(5) UNSIGNED ZEROFILL NULL,
  PRIMARY KEY (`id_location`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`IMAGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`IMAGES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`IMAGES` (
  `id_image` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `path_location` VARCHAR(100) NULL,
  `create_date` DATETIME NULL,
  `modify_date` DATETIME NULL,
  `delete_date` DATETIME NULL,
  `format_image` VARCHAR(45) NULL,
  `size_image` FLOAT NULL,
  PRIMARY KEY (`id_image`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`POSTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`POSTS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`POSTS` (
  `id_post` INT(5) NOT NULL AUTO_INCREMENT,
  `create_date` DATETIME NULL DEFAULT NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  `delete_date` DATETIME NULL DEFAULT NULL,
  `comment` VARCHAR(45) NULL DEFAULT NULL,
  `title` VARCHAR(45) NULL,
  `id_image` INT(5) NULL,
  PRIMARY KEY (`id_post`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`STATUS_ITEMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`STATUS_ITEMS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`STATUS_ITEMS` (
  `id_status_item` INT(5) NOT NULL AUTO_INCREMENT,
  `name_status` VARCHAR(45) NULL DEFAULT NULL,
  `code_status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_status_item`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`USERS_FEEDBACK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`USERS_FEEDBACK` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`USERS_FEEDBACK` (
  `id_user_feedback` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `comment` VARCHAR(45) NULL DEFAULT NULL,
  `score` VARCHAR(45) NULL DEFAULT NULL,
  `create_date` DATETIME NOT NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  `delete_time` DATETIME NULL DEFAULT NULL,
  `id_user` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `id_feedback` INT(4) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id_user_feedback`, `id_user`, `id_feedback`),
  UNIQUE INDEX `id_users_feedback_UNIQUE` (`id_user_feedback` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`LEND_ITEMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`LEND_ITEMS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`LEND_ITEMS` (
  `id_lend_item` INT(5) NOT NULL AUTO_INCREMENT,
  `status_lend_item` VARCHAR(45) NULL COMMENT ' Livre, Emprestado, En Negociacao',
  `lend_create_date` VARCHAR(45) NULL,
  `lend_modify_date` VARCHAR(45) NULL,
  `lend_finish_date` VARCHAR(45) NULL,
  `id_user_neighbor` INT(5) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id_lend_item`, `id_user_neighbor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`USERS_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`USERS_ITEM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`USERS_ITEM` (
  `id_user_item` INT(5) NOT NULL AUTO_INCREMENT,
  `create_date` DATETIME NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  `delete_time` DATETIME NULL DEFAULT NULL,
  `id_item` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `id_user_owner` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `id_lend_item` INT NULL,
  PRIMARY KEY (`id_user_item`, `id_item`, `id_user_owner`),
  UNIQUE INDEX `id_user_item_UNIQUE` (`id_user_item` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`USERS_POSTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`USERS_POSTS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`USERS_POSTS` (
  `id_user_post` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `create_date` DATETIME NOT NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  `delete_date` DATETIME NULL DEFAULT NULL,
  `id_user` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `id_post` INT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id_user_post`, `id_user`, `id_post`),
  UNIQUE INDEX `id_user_post_UNIQUE` (`id_user_post` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`USERS_FAVORITES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`USERS_FAVORITES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`USERS_FAVORITES` (
  `id_user_favorite` INT(5) NOT NULL AUTO_INCREMENT,
  `create_date` DATETIME NULL,
  `id_user` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `id_favorite` INT(10) UNSIGNED NOT NULL,
  `id_post` INT(5) UNSIGNED NULL,
  `id_item` INT(5) NULL,
  PRIMARY KEY (`id_user_favorite`, `id_user`, `id_favorite`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinho_online`.`ITEMS_IMAGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinho_online`.`ITEMS_IMAGES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinho_online`.`ITEMS_IMAGES` (
  `id_item_image` INT NOT NULL AUTO_INCREMENT,
  `IMAGES_id_image` INT(5) NOT NULL,
  `id_item` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `id_status` INT(11) NOT NULL,
  PRIMARY KEY (`id_item_image`, `IMAGES_id_image`, `id_item`, `id_status`))
ENGINE = InnoDB;

SHOW WARNINGS;
USE `vizinho_online`;

DELIMITER $$

USE `vizinho_online`$$
DROP TRIGGER IF EXISTS `vizinho_online`.`score` $$
SHOW WARNINGS$$
USE `vizinho_online`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `vizinho_online`.`score`
BEFORE INSERT ON `vizinho_online`.`FEEDBACKS`
FOR EACH ROW
BEGIN
  IF NEW.score<0 OR NEW.score>50 THEN
    CALL `Error: Wrong values for score, valid 0-5`; -- this trick will throw an error
  END IF;
END$$

SHOW WARNINGS$$

USE `vizinho_online`$$
DROP TRIGGER IF EXISTS `vizinho_online`.`score_update` $$
SHOW WARNINGS$$
USE `vizinho_online`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `vizinho_online`.`score_update`
BEFORE UPDATE ON `vizinho_online`.`FEEDBACKS`
FOR EACH ROW
BEGIN
  IF NEW.score<0 OR NEW.score>50 THEN
    CALL `Error: Wrong values for score, valid 0-5`; -- needs a valid score
  END IF;
END$$

SHOW WARNINGS$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
