-- MySQL Script generated by MySQL Workbench
-- Sat Jul  4 18:46:38 2020
-- Model: VizinhoOnline_v3    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vizinhonline
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vizinhonline` ;

-- -----------------------------------------------------
-- Schema vizinhonline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vizinhonline` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `vizinhonline` ;

-- -----------------------------------------------------
-- Table `CATEGORIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CATEGORIES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CATEGORIES` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `category_code` VARCHAR(200) NULL DEFAULT NULL,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_category_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `FAVORITES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FAVORITES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `FAVORITES` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_favorite_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `FEEDBACKS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FEEDBACKS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `FEEDBACKS` (
  `id` INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `comment` VARCHAR(200) NULL DEFAULT NULL,
  `score` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_feedback_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ITEMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITEMS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ITEMS` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL COMMENT 'full description of the item',
  `tax_fee` FLOAT NULL DEFAULT NULL COMMENT 'Price that will be charged by the item',
  `internal_notes` VARCHAR(200) NULL DEFAULT NULL COMMENT 'This field will be used by the system and administrators.',
  `feedback_score` INT(11) NULL DEFAULT NULL,
  `units` INT(5) ZEROFILL NULL DEFAULT NULL,
  `loan_start_date` DATETIME NULL DEFAULT NULL,
  `loan_end_date` DATETIME NULL DEFAULT NULL,
  `replacement_cost` FLOAT NULL DEFAULT NULL,
  `itemstatus_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `itemstatus_id`),
  UNIQUE INDEX `id_Item_UNIQUE` (`id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USERS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `USERS` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL,
  `email_verified_at` DATETIME NULL,
  `password` VARCHAR(200) NULL,
  `cellphone` VARCHAR(50) NULL,
  `rg` VARCHAR(50) NULL,
  `cpf` VARCHAR(45) NULL,
  `age` INT(11) NULL DEFAULT NULL,
  `ranking` TINYINT(4) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  `remember_token` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `FEEDBACK_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FEEDBACK_ITEM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `FEEDBACK_ITEM` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `item_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `feedback_id` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `user_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `item_id`, `feedback_id`, `user_id`),
  UNIQUE INDEX `id_Item_feedback_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `CATEGORY_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CATEGORY_ITEM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CATEGORY_ITEM` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'foreign key category',
  `category_id` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `item_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`category_id`, `item_id`),
  UNIQUE INDEX `id_item_category_UNIQUE` (`id` ASC),
  INDEX `fk_ITEM_CATEGORY_CATEGORIES1_idx` (`category_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `LOCATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LOCATIONS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `LOCATIONS` (
  `id` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `apartment_number` INT(11) NULL,
  `building` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `intercom_branch` INT(11) NULL DEFAULT NULL,
  `user_id` INT(5) UNSIGNED ZEROFILL NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IMAGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IMAGES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IMAGES` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `slug` VARCHAR(150) NULL,
  `path_location` VARCHAR(100) NULL,
  `format_image` VARCHAR(45) NULL,
  `size_image` FLOAT NULL,
  `user_id` INT(5) UNSIGNED ZEROFILL NULL,
  `post_id` INT(5) UNSIGNED NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC),
  UNIQUE INDEX `post_id_UNIQUE` (`post_id` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `POSTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `POSTS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `POSTS` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `comment` VARCHAR(200) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  `IMAGES_id` INT(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ITEM_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITEM_STATUS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ITEM_STATUS` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `FEEDBACK_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FEEDBACK_USER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `FEEDBACK_USER` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `comment` VARCHAR(45) NULL DEFAULT NULL,
  `score` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `user_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `feedback_id` INT(4) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `feedback_id`),
  UNIQUE INDEX `id_users_feedback_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `LEND_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LEND_ITEM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `LEND_ITEM` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL COMMENT ' Livre, Emprestado, En Negociacao',
  `lend_start_date` DATETIME NULL,
  `lend_modify_date` DATETIME NULL,
  `lend_finish_date` DATETIME NULL,
  `user_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `ITEM_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ITEM_USER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ITEM_USER` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `lenditem_id` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `item_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `user_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`, `item_id`, `user_id`),
  UNIQUE INDEX `id_user_item_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `USER_POST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USER_POST` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `USER_POST` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `post_id` INT UNSIGNED ZEROFILL NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `user_id`, `post_id`),
  UNIQUE INDEX `id_user_post_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `FAVORITE_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FAVORITE_USER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `FAVORITE_USER` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `user_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `favorite_id` INT(10) NOT NULL,
  `post_id` INT(5) UNSIGNED NULL,
  `item_id` INT(5) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `user_id`, `favorite_id`),
  UNIQUE INDEX `id_favorite_UNIQUE` (`favorite_id` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `IMAGE_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IMAGE_ITEM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `IMAGE_ITEM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image_id` INT(5) NOT NULL,
  `item_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `itemstatus_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `image_id`, `item_id`, `itemstatus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
