-- MySQL Script generated by MySQL Workbench
-- Tue May 19 09:53:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vizinhoOnline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vizinhoOnline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vizinhoOnline` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema vizinho_online
-- -----------------------------------------------------
USE `vizinhoOnline` ;

-- -----------------------------------------------------
-- Table `vizinhoOnline`.`STATUSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`STATUSES` (
  `id_status` INT NOT NULL AUTO_INCREMENT,
  `name_status` VARCHAR(45) NULL,
  `code_status` VARCHAR(45) NULL,
  PRIMARY KEY (`id_status`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`ITEMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`ITEMS` (
  `id_item` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(200) NULL,
  `code` VARCHAR(45) NULL,
  `status_code` VARCHAR(15) NULL,
  `create_date` DATETIME NOT NULL,
  `modify_date` DATETIME NULL,
  `delete_date` DATETIME NULL,
  `long_description` TEXT(2500) NULL COMMENT 'full description of the item',
  `tax_fee` VARCHAR(45) NULL COMMENT 'Price that will be charged by the item',
  `internal_notes` VARCHAR(200) NULL COMMENT 'This field will be used by the system and administrators.',
  `feedback_score` INT NULL,
  `units` VARCHAR(45) NULL,
  `loan_start_date` DATETIME NULL,
  `loan_end_date` DATETIME NULL,
  `replacement_cost` FLOAT NULL,
  `STATUSES_id_status` INT NOT NULL,
  PRIMARY KEY (`id_item`, `STATUSES_id_status`),
  UNIQUE INDEX `id_Item_UNIQUE` (`id_item` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  INDEX `fk_ITEMS_STATUSES1_idx` (`STATUSES_id_status` ASC),
  CONSTRAINT `fk_ITEMS_STATUSES1`
    FOREIGN KEY (`STATUSES_id_status`)
    REFERENCES `vizinhoOnline`.`STATUSES` (`id_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`CATEGORIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`CATEGORIES` (
  `id_category` INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `category_code` VARCHAR(200) NULL,
  `name` INT NULL,
  `description` VARCHAR(200) NULL,
  `create_date` DATETIME NOT NULL,
  `modify_date` DATETIME NULL,
  `delete_date` DATETIME NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `id_category_UNIQUE` (`id_category` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`ITEM_CATEGORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`ITEM_CATEGORY` (
  `id_item_category` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'foreign key category',
  `create_date` DATETIME NOT NULL,
  `modify_date` DATETIME NULL,
  `delete_date` DATETIME NULL,
  `CATEGORIES_id_category` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `ITEMS_id_item` INT(5) UNSIGNED ZEROFILL NOT NULL,
  UNIQUE INDEX `id_item_category_UNIQUE` (`id_item_category` ASC),
  INDEX `fk_ITEM_CATEGORY_CATEGORIES1_idx` (`CATEGORIES_id_category` ASC),
  INDEX `fk_ITEM_CATEGORY_ITEMS1_idx` (`ITEMS_id_item` ASC),
  PRIMARY KEY (`CATEGORIES_id_category`, `ITEMS_id_item`),
  CONSTRAINT `fk_ITEM_CATEGORY_CATEGORIES1`
    FOREIGN KEY (`CATEGORIES_id_category`)
    REFERENCES `vizinhoOnline`.`CATEGORIES` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEM_CATEGORY_ITEMS1`
    FOREIGN KEY (`ITEMS_id_item`)
    REFERENCES `vizinhoOnline`.`ITEMS` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`FEEDBACKS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`FEEDBACKS` (
  `id_feedback` INT(4) ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `comment` VARCHAR(200) NULL,
  `score` INT NULL,
  `create_date` DATETIME NOT NULL,
  `modify_date` DATETIME NULL,
  `delete_date` DATETIME NULL,
  PRIMARY KEY (`id_feedback`),
  UNIQUE INDEX `id_feedback_UNIQUE` (`id_feedback` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`POSTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`POSTS` (
  `id_post` DOUBLE UNSIGNED NOT NULL,
  `create_date` DATETIME NULL,
  `modify_date` DATETIME NULL,
  `delete_date` DATETIME NULL,
  `comment` VARCHAR(45) NULL,
  `title` VARCHAR(45) NOT NULL,
  `POSTScol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_post`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`USERS_POSTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`USERS_POSTS` (
  `id_user_post` INT UNSIGNED NOT NULL,
  `create_date` DATETIME NOT NULL,
  `modify_date` DATETIME NULL,
  `delete_date` DATETIME NULL,
  `USERS_id_user` INT(5) ZEROFILL UNSIGNED NOT NULL,
  `POSTS_id_posts` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user_post`, `USERS_id_user`, `POSTS_id_posts`),
  INDEX `fk_USERS_POSTS_USERS1_idx` (`USERS_id_user` ASC),
  INDEX `fk_USERS_POSTS_POSTS1_idx` (`POSTS_id_posts` ASC),
  UNIQUE INDEX `id_user_post_UNIQUE` (`id_user_post` ASC),
  CONSTRAINT `fk_USERS_POSTS_USERS1`
    FOREIGN KEY (`USERS_id_user`)
    REFERENCES `vizinhoOnline`.`USERS` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_POSTS_POSTS1`
    FOREIGN KEY (`POSTS_id_posts`)
    REFERENCES `vizinhoOnline`.`POSTS` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`IMAGES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`IMAGES` (
  `id_image` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `path_location` VARCHAR(45) NULL,
  `create_date` DATETIME NULL,
  `modify_date` DATETIME NULL,
  `delete_date` DATETIME NULL,
  `USERS_POSTS_id_user_post` INT UNSIGNED NOT NULL,
  `USERS_POSTS_USERS_id_user` INT(5) ZEROFILL UNSIGNED NOT NULL,
  `USERS_POSTS_POSTS_id_posts` DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (`id_image`, `USERS_POSTS_id_user_post`, `USERS_POSTS_USERS_id_user`, `USERS_POSTS_POSTS_id_posts`),
  INDEX `fk_IMAGES_USERS_POSTS1_idx` (`USERS_POSTS_id_user_post` ASC, `USERS_POSTS_USERS_id_user` ASC, `USERS_POSTS_POSTS_id_posts` ASC),
  UNIQUE INDEX `id_image_UNIQUE` (`id_image` ASC),
  CONSTRAINT `fk_IMAGES_USERS_POSTS1`
    FOREIGN KEY (`USERS_POSTS_id_user_post` , `USERS_POSTS_USERS_id_user` , `USERS_POSTS_POSTS_id_posts`)
    REFERENCES `vizinhoOnline`.`USERS_POSTS` (`id_user_post` , `USERS_id_user` , `POSTS_id_posts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`USERS` (
  `id_user` INT(5) ZEROFILL UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `ranking` VARCHAR(45) NULL,
  `IMAGES_id_images` INT UNSIGNED NOT NULL,
  `create_date` DATETIME NOT NULL,
  `modify_date` DATETIME NULL,
  `delete_date` DATETIME NULL,
  `USERS_id_user` INT(5) ZEROFILL UNSIGNED NOT NULL,
  `USERS_IMAGES_id_images` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user`, `IMAGES_id_images`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_USERS_IMAGES1_idx` (`IMAGES_id_images` ASC),
  INDEX `fk_USERS_USERS1_idx` (`USERS_id_user` ASC, `USERS_IMAGES_id_images` ASC),
  CONSTRAINT `fk_USERS_IMAGES1`
    FOREIGN KEY (`IMAGES_id_images`)
    REFERENCES `vizinhoOnline`.`IMAGES` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_USERS1`
    FOREIGN KEY (`USERS_id_user` , `USERS_IMAGES_id_images`)
    REFERENCES `vizinhoOnline`.`USERS` (`id_user` , `IMAGES_id_images`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`ITEMS_FEEDBACK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`ITEMS_FEEDBACK` (
  `id_item_feedback` INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `create_date` DATETIME NOT NULL,
  `modify_date` DATETIME NULL,
  `delete_date` DATETIME NULL,
  `ITEMS_id_item` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `FEEDBACKS_id_feedback` INT(4) ZEROFILL UNSIGNED NOT NULL,
  `USERS_id_user` INT(5) ZEROFILL UNSIGNED NOT NULL,
  `USERS_IMAGES_id_images` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_item_feedback`, `ITEMS_id_item`, `FEEDBACKS_id_feedback`, `USERS_id_user`, `USERS_IMAGES_id_images`),
  UNIQUE INDEX `id_Item_feedback_UNIQUE` (`id_item_feedback` ASC),
  INDEX `fk_ITEM_FEEDBACK_ITEMS_idx` (`ITEMS_id_item` ASC),
  INDEX `fk_ITEM_FEEDBACK_FEEDBACKS1_idx` (`FEEDBACKS_id_feedback` ASC),
  INDEX `fk_ITEMS_FEEDBACK_USERS1_idx` (`USERS_id_user` ASC, `USERS_IMAGES_id_images` ASC),
  CONSTRAINT `fk_ITEM_FEEDBACK_ITEMS`
    FOREIGN KEY (`ITEMS_id_item`)
    REFERENCES `vizinhoOnline`.`ITEMS` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEM_FEEDBACK_FEEDBACKS1`
    FOREIGN KEY (`FEEDBACKS_id_feedback`)
    REFERENCES `vizinhoOnline`.`FEEDBACKS` (`id_feedback`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEMS_FEEDBACK_USERS1`
    FOREIGN KEY (`USERS_id_user` , `USERS_IMAGES_id_images`)
    REFERENCES `vizinhoOnline`.`USERS` (`id_user` , `IMAGES_id_images`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`USERS_FEEDBACK`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`USERS_FEEDBACK` (
  `id_user_feedback` INT UNSIGNED NOT NULL,
  `title` VARCHAR(45) NULL,
  `comment` VARCHAR(45) NULL,
  `score` VARCHAR(45) NULL,
  `create_date` DATETIME NOT NULL,
  `modify_date` DATETIME NULL,
  `delete_time` DATETIME NULL,
  `USERS_id_user` INT(5) ZEROFILL UNSIGNED NOT NULL,
  `FEEDBACKS_id_feedback` INT(4) ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user_feedback`, `FEEDBACKS_id_feedback`, `USERS_id_user`),
  UNIQUE INDEX `id_users_feedback_UNIQUE` (`id_user_feedback` ASC),
  INDEX `fk_USERS_FEEDBACK_USERS1_idx` (`USERS_id_user` ASC),
  INDEX `fk_USERS_FEEDBACK_FEEDBACKS1_idx` (`FEEDBACKS_id_feedback` ASC),
  CONSTRAINT `fk_USERS_FEEDBACK_USERS1`
    FOREIGN KEY (`USERS_id_user`)
    REFERENCES `vizinhoOnline`.`USERS` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_FEEDBACK_FEEDBACKS1`
    FOREIGN KEY (`FEEDBACKS_id_feedback`)
    REFERENCES `vizinhoOnline`.`FEEDBACKS` (`id_feedback`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`USERS_ITEM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`USERS_ITEM` (
  `id_user_item` INT NOT NULL AUTO_INCREMENT,
  `create_date` DATETIME NOT NULL,
  `modify_date` DATETIME NULL,
  `delete_time` DATETIME NULL,
  `imagem` VARCHAR(45) NULL,
  `ITEMS_id_item` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `USERS_id_user` INT(5) ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user_item`, `ITEMS_id_item`, `USERS_id_user`),
  UNIQUE INDEX `id_user_item_UNIQUE` (`id_user_item` ASC),
  INDEX `fk_USER_ITEM_ITEMS1_idx` (`ITEMS_id_item` ASC),
  INDEX `fk_USER_ITEM_USERS1_idx` (`USERS_id_user` ASC),
  CONSTRAINT `fk_USER_ITEM_ITEMS1`
    FOREIGN KEY (`ITEMS_id_item`)
    REFERENCES `vizinhoOnline`.`ITEMS` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_ITEM_USERS1`
    FOREIGN KEY (`USERS_id_user`)
    REFERENCES `vizinhoOnline`.`USERS` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`LOCATIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`LOCATIONS` (
  `id_location` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `apartment_number` INT NOT NULL,
  `build` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `intercom_branch` INT NULL,
  `USERS_id_user` INT(5) ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`id_location`, `USERS_id_user`),
  INDEX `fk_LOCATIONS_USERS1_idx` (`USERS_id_user` ASC),
  CONSTRAINT `fk_LOCATIONS_USERS1`
    FOREIGN KEY (`USERS_id_user`)
    REFERENCES `vizinhoOnline`.`USERS` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`FAVORITES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`FAVORITES` (
  `id_favorite` INT UNSIGNED NOT NULL,
  `FAVORITEScol` VARCHAR(45) NULL,
  `status_favorite` VARCHAR(45) NULL,
  PRIMARY KEY (`id_favorite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`USERS_FAVORITES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`USERS_FAVORITES` (
  `id_user_favorite` INT UNSIGNED NOT NULL,
  `create_date` DATETIME NULL,
  `USERS_POSTS_id_users_posts` INT UNSIGNED NOT NULL,
  `USERS_POSTS_USERS_id_user` INT(5) ZEROFILL UNSIGNED NOT NULL,
  `USERS_POSTS_POSTS_id_posts` DOUBLE UNSIGNED NOT NULL,
  `FAVORITES_id_favorites` INT UNSIGNED NOT NULL,
  `USERS_ITEM_id_user_item` INT NOT NULL,
  `USERS_ITEM_ITEMS_id_item` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `USERS_ITEM_USERS_id_user` INT(5) ZEROFILL UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user_favorite`, `USERS_POSTS_id_users_posts`, `USERS_POSTS_USERS_id_user`, `USERS_POSTS_POSTS_id_posts`, `FAVORITES_id_favorites`, `USERS_ITEM_id_user_item`, `USERS_ITEM_ITEMS_id_item`, `USERS_ITEM_USERS_id_user`),
  INDEX `fk_USERS_FAVORITES_USERS_POSTS1_idx` (`USERS_POSTS_id_users_posts` ASC, `USERS_POSTS_USERS_id_user` ASC, `USERS_POSTS_POSTS_id_posts` ASC),
  INDEX `fk_USERS_FAVORITES_FAVORITES1_idx` (`FAVORITES_id_favorites` ASC),
  INDEX `fk_USERS_FAVORITES_USERS_ITEM1_idx` (`USERS_ITEM_id_user_item` ASC, `USERS_ITEM_ITEMS_id_item` ASC, `USERS_ITEM_USERS_id_user` ASC),
  CONSTRAINT `fk_USERS_FAVORITES_USERS_POSTS1`
    FOREIGN KEY (`USERS_POSTS_id_users_posts` , `USERS_POSTS_USERS_id_user` , `USERS_POSTS_POSTS_id_posts`)
    REFERENCES `vizinhoOnline`.`USERS_POSTS` (`id_user_post` , `USERS_id_user` , `POSTS_id_posts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_FAVORITES_FAVORITES1`
    FOREIGN KEY (`FAVORITES_id_favorites`)
    REFERENCES `vizinhoOnline`.`FAVORITES` (`id_favorite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_FAVORITES_USERS_ITEM1`
    FOREIGN KEY (`USERS_ITEM_id_user_item` , `USERS_ITEM_ITEMS_id_item` , `USERS_ITEM_USERS_id_user`)
    REFERENCES `vizinhoOnline`.`USERS_ITEM` (`id_user_item` , `ITEMS_id_item` , `USERS_id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vizinhoOnline`.`ITEM_IMAGES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vizinhoOnline`.`ITEM_IMAGES` (
  `id_item_image` INT NOT NULL AUTO_INCREMENT,
  `ITEMS_id_item` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `IMAGES_id_image` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_item_image`, `ITEMS_id_item`, `IMAGES_id_image`),
  INDEX `fk_ITEM_IMAGES_ITEMS1_idx` (`ITEMS_id_item` ASC),
  INDEX `fk_ITEM_IMAGES_IMAGES1_idx` (`IMAGES_id_image` ASC),
  UNIQUE INDEX `id_item_image_UNIQUE` (`id_item_image` ASC),
  CONSTRAINT `fk_ITEM_IMAGES_ITEMS1`
    FOREIGN KEY (`ITEMS_id_item`)
    REFERENCES `vizinhoOnline`.`ITEMS` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEM_IMAGES_IMAGES1`
    FOREIGN KEY (`IMAGES_id_image`)
    REFERENCES `vizinhoOnline`.`IMAGES` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
