-- MySQL Script generated by MySQL Workbench
-- Mon Jun 22 21:54:56 2020
-- Model: VizinhoOnline_v3    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vizinhonline
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vizinhonline` ;

-- -----------------------------------------------------
-- Schema vizinhonline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vizinhonline` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `vizinhonline` ;

-- -----------------------------------------------------
-- Table `vizinhonline`.`CATEGORIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`CATEGORIES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`CATEGORIES` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `category_code` VARCHAR(200) NULL DEFAULT NULL,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_category_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`FAVORITES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`FAVORITES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`FAVORITES` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `create_date` DATETIME NULL DEFAULT NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  `delete_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_favorite_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`FEEDBACKS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`FEEDBACKS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`FEEDBACKS` (
  `id` INT(4) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `comment` VARCHAR(200) NULL DEFAULT NULL,
  `score` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_feedback_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`ITEMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`ITEMS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`ITEMS` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL COMMENT 'full description of the item',
  `tax_fee` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Price that will be charged by the item',
  `internal_notes` VARCHAR(200) NULL DEFAULT NULL COMMENT 'This field will be used by the system and administrators.',
  `feedback_score` INT(11) NULL DEFAULT NULL,
  `units` VARCHAR(45) NULL DEFAULT NULL,
  `loan_start_date` DATETIME NULL DEFAULT NULL,
  `loan_end_date` DATETIME NULL DEFAULT NULL,
  `replacement_cost` FLOAT NULL DEFAULT NULL,
  `itemstatus_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `itemstatus_id`),
  UNIQUE INDEX `id_Item_UNIQUE` (`id` ASC),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`USERS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`USERS` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(200) NULL,
  `cellphone` VARCHAR(50) NULL,
  `rg` VARCHAR(50) NULL,
  `cpf` VARCHAR(45) NULL,
  `age` INT(11) UNSIGNED NULL DEFAULT NULL,
  `ranking` TINYINT(4) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`FEEDBACK_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`FEEDBACK_ITEM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`FEEDBACK_ITEM` (
  `id` INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `item_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `feedback_id` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `user_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `item_id`, `feedback_id`, `user_id`),
  UNIQUE INDEX `id_Item_feedback_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`CATEGORY_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`CATEGORY_ITEM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`CATEGORY_ITEM` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'foreign key category',
  `category_id` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `item_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`category_id`, `item_id`),
  UNIQUE INDEX `id_item_category_UNIQUE` (`id` ASC),
  INDEX `fk_ITEM_CATEGORY_CATEGORIES1_idx` (`category_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`LOCATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`LOCATIONS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`LOCATIONS` (
  `id` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `apartment_number` INT(11) NULL,
  `building` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `intercom_branch` INT(11) NULL DEFAULT NULL,
  `user_id` INT(5) UNSIGNED ZEROFILL NULL,
  `create_date` DATETIME NULL DEFAULT NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  `delete_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`IMAGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`IMAGES` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`IMAGES` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `slug` VARCHAR(150) NULL,
  `path_location` VARCHAR(100) NULL,
  `format_image` VARCHAR(45) NULL,
  `size_image` FLOAT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`POSTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`POSTS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`POSTS` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `comment` VARCHAR(200) NULL DEFAULT NULL,
  `image_id` INT(5) NULL,
  `create_date` DATETIME NULL DEFAULT NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  `delete_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`ITEM_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`ITEM_STATUS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`ITEM_STATUS` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `code` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`FEEDBACK_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`FEEDBACK_USER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`FEEDBACK_USER` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL DEFAULT NULL,
  `comment` VARCHAR(45) NULL DEFAULT NULL,
  `score` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `user_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `feedback_id` INT(4) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `feedback_id`),
  UNIQUE INDEX `id_users_feedback_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`LEND_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`LEND_ITEM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`LEND_ITEM` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NULL COMMENT ' Livre, Emprestado, En Negociacao',
  `lend_start_date` DATETIME NULL,
  `lend_modify_date` DATETIME NULL,
  `lend_finish_date` DATETIME NULL,
  `user_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `user_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`ITEM_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`ITEM_USER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`ITEM_USER` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `lenditem_id` INT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `items_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `users_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`id`, `items_id`, `users_id`),
  UNIQUE INDEX `id_user_item_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`USER_POST`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`USER_POST` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`USER_POST` (
  `id` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `post_id` INT UNSIGNED ZEROFILL NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `user_id`, `post_id`),
  UNIQUE INDEX `id_user_post_UNIQUE` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`FAVORITE_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`FAVORITE_USER` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`FAVORITE_USER` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `user_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `favorite_id` INT(10) NOT NULL,
  `post_id` INT(5) UNSIGNED NULL,
  `item_id` INT(5) NULL,
  `create_date` DATETIME NULL DEFAULT NULL,
  `modify_date` DATETIME NULL DEFAULT NULL,
  `delete_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `user_id`, `favorite_id`),
  UNIQUE INDEX `id_favorite_UNIQUE` (`favorite_id` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `vizinhonline`.`IMAGE_ITEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vizinhonline`.`IMAGE_ITEM` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `vizinhonline`.`IMAGE_ITEM` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image_id` INT(5) NOT NULL,
  `item_id` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `itemstatus_id` INT(11) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`, `image_id`, `item_id`, `itemstatus_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
